version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/api/users/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - USERSERVICE_URL=http://user-service:8081
    depends_on:
      user-service:
        condition: service_healthy
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8082/api/orders/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s

networks:
  microservices-network:
    driver: bridge